min_distance: 0.375
max_distance: 3.0
num_points: 0
sub_topics: [ '/laser/scan', '/stereo_1/disparity', '/stereo_2/disparity', '/stereo_3/disparity', '/stereo_4/disparity' ]
pub_topic: 'sensor_readings'
max_time: 1.0
frequency: 10.0
